### ISSUE TITLE
'module' object has no attribute 'BinaryField'

### ISSUE THREAD

**Issue by xiongzhp** [rdkit/OCEAN#5]

**Comment by wolfguidobolick** [comment]
Which Django-Version do you use?

**Comment by xiongzhp** [comment]
Thanks, after I update Django to 1.7.1, it works. But when I try with the SMILES "Cc1nc(Nc2ncc(s2)C(=O)Nc2c(C)cccc2Cl)cc(n1)N1CCN(CCO)CC1", the results page only shows header bar.

**Comment by xiongzhp** [comment]
Exception: Didn't found datasourceCHEMBL,fp6,thresh0.3 in FP_Parameter

**Comment by wolfguidobolick** [comment]
did you follow the instructions for setting up ocean? in particular:

-python manage.py runserver 0.0.0.0:8080

and

The next steps are necessary to create the fingerprints for all structures: 1. Login to ocean-admin portal http://0.0.0.0:8080/admin
Select CHEMBL and 6 (section a), press createFPs to create Morgan-Fingerprints for all entries. This may take a few minutes. You should see a message at the bottom of the site when the process is done.

then wait few minutes till you got a message on the django-admin site and
then do

The last step is calculating the statistical parameters for OCEAN's scoring-function: 1. In the Django-Admin portal select CHEMBL, 6 and activate Checkbox rebuild Pairs (section b), press recalc Statistics for Fingerprint and Datasource to calculate statistic-parameters for the scoring-function. This will also take a few minutes. Wait until you see a new message at the bottom of the site.

this may also take a few minutes, please double check that you did these steps and no errors happened

**Comment by xiongzhp** [comment]
Thanks, it works
